apiVersion: v1
kind: ConfigMap
metadata:
  name: dms-azure-configmap
  namespace: dms-dev
data:
  AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
  AZURE_JWK_SET_URI: "https://login.microsoftonline.com/${AZURE_TENANT_ID}/discovery/v2.0/keys"
  AZURE_KEYVAULT_URI: "https://dms-keyvault-dev.vault.azure.net"
