apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: dms-frontend-service-internal
  namespace: dms-prod-frontend
spec:
  hosts:
    - "dms.prod.lvad.lvfs.net"
  gateways:
    - istio-ingress-internal/default-gateway-prod-internal
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: dms-frontend-service.dms-prod-frontend.svc.cluster.local
            port:
              number: 8080
      timeout: 120s
      corsPolicy:
        allowOrigins:
          - exact: https://dms.prod.lvad.lvfs.net
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PATCH
          - PUT
          - DELETE
        allowHeaders:
          - Authorization
          - Content-Type
          - Accept
          - Origin
          - User-Agent
        allowCredentials: true
